### ISSUE TITLE
Add License file

### ISSUE THREAD

**Issue by danny-laa** [PotatoProject/Leaflet#12]
> You can use the code freely, the only thing you should do is credit me in some way (and maybe link to this repo) but that's it, for the rest you're free to do whatever you want
> 
> _Originally posted by @HrX03 in https://github.com/HrX03/PotatoNotes/issues/8#issuecomment-571927204_

A project cannot considered free and open source without a license file.

If the only thing you require is just attribution of your name, [MIT License](https://choosealicense.com/licenses/mit/) would be a good license.

I can help create a pull request if you need help with it.

**Comment by dvd-bnc** [comment]
That seems cool, I never added a license to a project so if you could do a pr to lemme see how it is done, that would be really cool

**Comment by danny-laa** [comment]
> That seems cool, I never added a license to a project so if you could do a pr to lemme see how it is done, that would be really cool

Thx. I created a pull request or it. See #13 

Every redistribution of your code will be required to include the license file, which contains your name :)
