### ISSUE TITLE
The german(deutsch) translation file contains the dutch translations

### ISSUE THREAD

**Issue by broodroosterdev** [PotatoProject/Leaflet#15]
The file intl_de.arb should either be renamed to intl_nl.arb or the intl_de.arb should contain the german (Deutsch) translations

**Comment by dvd-bnc** [comment]
ooh thanks for the report, crowdin actually told me that the deustch translation file was de so i put that, anyways will be fixing that

**Comment by dvd-bnc** [comment]
ok no i rechecked crowdin and im a dumbass, will update those for next update
