### ISSUE TITLE
Translations

### ISSUE THREAD

**Issue by mondlicht-und-sterne** [PotatoProject/Leaflet#16]
there are several translation tools. 
[weblate](https://hosted.weblate.org/) 
[crowdin](https://crowdin.com/) 
[poeditor](https://poeditor.com/) 
[transifex](https://www.transifex.com/)

it would be easier than at github
I'm writing down my experiences here. But you have to decide what you want.
if you take value on opensource, you can use #weblate. otherwise i hang out a lot on #crowdin and #poeditor. poeditor is, that you can only translate if you know the link. in poeditor there is no overview of all created projects of all people. people who want to translate too, find your link only by chance. i think that's stupid.
at #transifex it can be that you are rejected or that it takes a long time until you are accepted.

**Comment by dvd-bnc** [comment]
we already got a crowdin here https://crowdin.com/project/potatonotes, thanks for the report anyways cuz i never mentioned it on github
