### ISSUE TITLE
Long notes don't scroll correctly

### ISSUE THREAD

**Issue by bejd** [PotatoProject/Leaflet#19]
Notes longer than 32 lines do not scroll when viewed. The only way to see the extra text is to edit the note, then use the text input cursor to scroll inside the text input box.

Device: Pixel 4 XL
OS: Android 10 (QQ1B.200205.002)
Potatonotes version: 1.5.1+13

Video demonstrating the issue:
https://youtu.be/g-DL0iISg7w

**Comment by dvd-bnc** [comment]
damn love the vid, i actually knew about the issue, but being the lazy ass that i am i just continued to procrastinate, should have a fix, will do asap

**Comment by gargakshit** [comment]
@HrX03 what is the status? lol

**Comment by dvd-bnc** [comment]
Fixed since long time ago, any branch but reference has the fix. Also closing
