### ISSUE TITLE
[Enhancement] List: Use "Enter" for new entry

### ISSUE THREAD

**Issue by ministryofsillywalks** [PotatoProject/Leaflet#24]
When creating a list it would make it a lot easier to be able to use the enter key to create a new entry.
Currently when creating a checklist you have to click on the "+" sign in the app for each new entry but it would be much easier and faster to just write one task, press enter and write the next task.

**Comment by LPkkjHD** [comment]
addressed in #26

**Comment by dvd-bnc** [comment]
done in https://github.com/HrX03/PotatoNotes/commit/fd16b59464c9b3cfbf1d04208f03241c325cb821
