### ISSUE TITLE
b/routes/settings_route.dart:486:65: Error: 

### ISSUE THREAD

**Issue by lucasjinreal** [PotatoProject/Leaflet#27]
b/routes/settings_route.dart:486:65: Error: The getter 'headline6' isn't defined for the class 'TextTheme'.
 - 'TextTheme' is from 'package:flutter/src/material/text_theme.dart' ('/E:/apps/flutter/packages/flutter/lib/src/material/text_theme.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'headline6'.
                                    Theme.of(context).textTheme.headline6.color)
                                                                ^^^^^^^^^
lib/routes/settings_route.dart:496:65: Error: The getter 'headline6' isn't defined for the class 'TextTheme'.
 - 'TextTheme' is from 'package:flutter/src/material/text_theme.dart' ('/E:/apps/flutter/packages/flutter/lib/src/material/text_theme.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'headline6'.
                                    Theme.of(context).textTheme.headline6.color)
                                                                ^^^^^^^^^
lib/ui/note_view.dart:36:51: Error: The getter 'headline6' isn't defined for the class 'TextTheme'.
 - 'TextTheme' is from 'package:flutter/src/material/text_theme.dart' ('/E:/apps/flutter/packages/flutter/lib/src/material/text_theme.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'headline6'.
    Color cardColor = Theme.of(context).textTheme.headline6.color;
                                                  ^^^^^^^^^
lib/ui/note_view.dart:63:46: Error: The getter 'headline6' isn't defined for the class 'TextTheme'.
 - 'TextTheme' is from 'package:flutter/src/material/text_theme.dart' ('/E:/apps/flutter/packages/flutter/lib/src/material/text_theme.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'headline6'.
          return Theme.of(context).textTheme.headline6.color;
                                             ^^^^^^^^^
lib/ui/note_view.dart:168:40: Error: The getter 'headline6' isn't defined for the class 'TextTheme'.
 - 'TextTheme' is from 'package:flutter/src/material/text_theme.dart' ('/E:/apps/flutter/packages/flutter/lib/src/material/text_theme.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'headline6'.
                                      .headline6
                                       ^^^^^^^^^
lib/ui/note_view.dart:186:40: Error: The getter 'headline6' isn't defined for the class 'TextTheme'.
 - 'TextTheme' is from 'package:flutter/src/material/text_theme.dart' ('/E:/apps/flutter/packages/flutter/lib/src/material/text_theme.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'headline6'.
                                      .headline6
                                       ^^^^^^^^^
lib/ui/note_view.dart:212:48: Error: The getter 'headline6' isn't defined for the class 'TextTheme'.

**Comment by dvd-bnc** [comment]
Please read carefully the readme, in particular the building part

**Comment by lucasjinreal** [comment]
```
[√] Flutter (Channel stable, v1.12.13+hotfix.8, on Microsoft Windows [Version 10.0.18362.720], locale zh-CN)

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
[!] Android Studio (version 3.6)
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
[√] VS Code (version 1.43.0)
[√] Connected device (1 available)

! Doctor found issues in 1 category.
```

**Comment by broodroosterdev** [comment]
You should use the master channel of flutter. You can switch to this with `flutter channel master` . Then, run all the commands again.
