### ISSUE TITLE
Notes which are not synced gets deleted on app launch

### ISSUE THREAD

**Issue by Gaurav192** [PotatoProject/Leaflet#29]
If parsed list != list then local entries are deleted and parsed list is entered again in db.

https://github.com/HrX03/PotatoNotes/blob/4738afb6d06413df4b8a9244e0ad47420a535bac/lib/routes/notes_main_page_route.dart#L342

**Comment by dvd-bnc** [comment]
to be honest i never noticed that and now that i think of it i could've done it much easier by just replacing the notes. Too bad that i wouldn't have any way to detect deleted notes, but still its useful to keep this in consideration for the new version

**Comment by Woytazzer** [comment]
Yes every time when i open app notes are gone from android device , not in trash or archive etc just gone .. Even withou sync.. :(

**Comment by dvd-bnc** [comment]
clsong cuz fixed with latest sync impl + dup of #9
