### ISSUE TITLE
Configure Custom Sync Server in Mobile App

### ISSUE THREAD

**Issue by mtdevans** [PotatoProject/Leaflet#31]
The sync server is open source and self-hostable, but cannot be pointed at in the mobile app's UI.

The goal of implementing this was mentioned in a [comment on a closed issue](https://github.com/HrX03/PotatoNotes/issues/1#issuecomment-597029378) but having an open issue makes tracking progress easier.

I would help with this but I don't have the requisite mobile dev knowledge at present.

**Comment by dvd-bnc** [comment]
if i remember correctly in the newer version of the app i already added this kind of feature, so you should be covered on that already. if thats not the case dont worry i already planned on adding it and will do so asap

**Comment by broodroosterdev** [comment]
In the rewrite we have the logic to store and use the custom API url. We only need to add it to the settingspage but this shouldn't be hard to do.
https://github.com/HrX03/PotatoNotes/blob/77631f355dd10feb7190d5c3e714c8b427a91b5d/lib/internal/preferences.dart#L60

**Comment by dvd-bnc** [comment]
for more info, refer to the commit https://github.com/HrX03/PotatoNotes/commit/4f3595ca569d5950742110d95440b19d92bdd40a

**Comment by broodroosterdev** [comment]
Changing to a custom api url

**Comment by broodroosterdev** [comment]
Changing to a custom api url is now possible via the settingspage, see [ea257ec](https://github.com/HrX03/PotatoNotes/commit/ea257eceb2e70d667fc559b7d1f44c8065bd1b46)

**Comment by gargakshit** [comment]
Should we close this?

**Comment by broodroosterdev** [comment]
I would close this issue since the feature that is asked for has been implemented. Any other request or issue related to a custom sync server should go in a separate issue.

**Comment by dvd-bnc** [comment]
Agree, closing
