### ISSUE TITLE
Cannot change username due to "malformed authentication token" 

### ISSUE THREAD

**Issue by AnonRS3** [PotatoProject/Leaflet#33]
As depicted below, if I attempt to change my username, I get an error message. It doesn't matter what I type in the text box, it always shows the error. 

![](https://i.imgur.com/XkcFSAX.jpg)

**Comment by dvd-bnc** [comment]
ooh this is interesting, it could actually be that the saved token on the app is corrupted or gone in some way, i'd suggest you try to log off and log in again and try to change the username, see if the issue still persists

**Comment by AnonRS3** [comment]
@HrX03 yep I tried logging out and in again, also clearing app data, unfortunately the issue persisted. I'll see if deleting and reinstalling the app helps in any way.

**Comment by dvd-bnc** [comment]
hm if you can could you build the app in debug mode and put a log statement in the change name function? will soon send you the exact code location and stuff

**Comment by dvd-bnc** [comment]
oh damn right remember to use master branch to build, rewrite doesnt have the same code

**Comment by dvd-bnc** [comment]
fuck im so stupid https://github.com/HrX03/PotatoNotes/blob/master/lib/routes/sync_manage_route.dart#L321, here im using the super old url for the api jesus christ. And that's why we now got a new rewrite branch lol, there are so many stuff wrong with the current app

**Comment by AnonRS3** [comment]
Ah, well glad to hear about the rewrite, that'll help fix those smaller issues that are easy to overlook sometimes. I can build the app later today, if still needed.

**Comment by dvd-bnc** [comment]
if you wish to there's no problem for me, but yea that branch is discontinued anyways so no need to make a pr or anything like that

**Comment by AnonRS3** [comment]
Oh okay sounds good. Thanks for looking into this. I use this app quite a lot so it's good to see there are fixes coming out 👍
