### ISSUE TITLE
flutter run error

### ISSUE THREAD

**Issue by goodforever** [PotatoProject/Leaflet#37]
flutter run
got 
Exception: Gradle build failed to produce an .apk file. It's likely that this
file was generated under /Users/foo/PotatoNotes/build, but the
tool couldn't find it.

**Comment by broodroosterdev** [comment]
Hi, this is likely because you did not specify a build flavor. Please try to add `--flavor dev` to the end of the build command.

**Comment by broodroosterdev** [comment]
I'll update the README to include this as well.

**Comment by goodforever** [comment]
@broodroosterdev Thanks ! successful
