### ISSUE TITLE
Copied content not showing up

### ISSUE THREAD

**Issue by GitterDoneBoi** [PotatoProject/Leaflet#39]
Hi! Just noticed this bug while using the app (absolutely beautiful UI btw, encryption pretty please?), whenever I copy a huge paragraph on one of the notes, it doesn't show it in its entirety (more like 1/10th of the whole thing). I can't even scroll down unless I go into edit mode. It's quite inconvenient to not be able to copy stuff since I do it pretty regularly, but your notes app is the most visually pleasing alternative to Keep. So it's kinda a shame that I can't use it as a daily for now.

Appreciate the great app though! You guys rock!

I hope the image attachment works, here's a comparison between Notally and POSP Note:
![IMG_20200724_181246](https://user-images.githubusercontent.com/67357310/88392260-4d7f3100-cdd9-11ea-8234-9741b27fd047.jpg)

**Comment by dvd-bnc** [comment]
Oh yea this is totally a bug in the legacy app version, but it has been fixed for quite some months now on the new app (which is set to release very soon), so dw about it as it won't be present in the next update

**Comment by GitterDoneBoi** [comment]
@HrX03 Damn that was a quick response :D 

Thanks! That's awesome news, I look forward to using it! I'll buy you a cup of coffee as soon as I have a bank account :p

**Comment by dvd-bnc** [comment]
this thing has been implemented for a lot of time so no point on keeping this open, closing
