### ISSUE TITLE
App crashes after setting up reminder

### ISSUE THREAD

**Issue by joshas** [PotatoProject/Leaflet#40]
Add new note, press "+", select "Reminder" to add new reminder. Select time, select date. Clicking "Save" app crashes and note dissapears.
PotatoNotes version 1.5.2+15, installed from Google Play Store.

**Comment by dvd-bnc** [comment]
this is because i was a dumbass and i didnt configure the notification plugin correctly, it'll be eventually fixed on v2 when we implement full reminder support

**Comment by joshas** [comment]
Will be patiently waiting for v2. With google keep not working correctly anymore this is app is probably the best replacement.

**Comment by dvd-bnc** [comment]
There are no reminders yet on the new version but i'll be extra sure the thing doesnt crash with the new impl, therefore closing
