### ISSUE TITLE
Android app has iOS-like scrolling

### ISSUE THREAD

**Issue by dz4k** [PotatoProject/Leaflet#41]
This feels like it's intentional, but the unusual scrolling behavior makes the app feel odd.

**Comment by dvd-bnc** [comment]
Yea it was by design choice but now I realize it breaks the native feel, on the new version I don't apply hard coded scrolling styles anymore but I use platform default so it should feel better

**Comment by dvd-bnc** [comment]
Has been solved on latest leaflet version, closing
