### ISSUE TITLE
Would it like add support for stable branch?

### ISSUE THREAD

**Issue by lucasjinreal** [PotatoProject/Leaflet#50]
Would it like add support for stable branch?

**Comment by dvd-bnc** [comment]
As of now we do need some stuff the master branch offers, but on next stable flutter I'll try to be compatible with it

**Comment by lucasjinreal** [comment]
@HrX03  thank u! that's really helpful. any time schedual on this?

**Comment by dvd-bnc** [comment]
New flutter stable should come out around February 2021, so you could expect support around there

**Comment by lucasjinreal** [comment]
@HrX03  thank u so much!
