### ISSUE TITLE
Save note when typing stops

### ISSUE THREAD

**Issue by rOOb85** [PotatoProject/Leaflet#60]
It would be great if notes were auto saved X seconds after typing stops. Sometimes I'll start a note then get distracted and put my phone in my pocket. If the app then gets killed, when I pull my phone out and restart the app...the note i was previously typing is gone.

I think it would be pretty easy to have a workflow like: 
Start new note
Start typing note
Stop typing note
Wait 5 seconds, if still not typing 
Save note

Just an idea, I appreciate the app either way!

**Comment by dvd-bnc** [comment]
We have instant saving as of now and we also had a working prototype of delays and stuff, therefore consider it done. Closing
