### ISSUE TITLE
Invalid flutter command in Readme.md

### ISSUE THREAD

**Issue by pagdot** [PotatoProject/Leaflet#69]
The Readme contains following instructions for building Leaflet:

> For now the required flutter channel is master, so issue those two commands before starting building:
>
> ```
> ~$ flutter channel master
> ~$ flutter update
> ```

When trying to run the second one, I get following output:

```
$ flutter update
Could not find a command named "update".


Run 'flutter -h' (or 'flutter <command> -h') for available flutter commands and options.
```

Do you mean to run `flutter upgrade`?

**Comment by dvd-bnc** [comment]
Oops yea, seems like i got it wrong, the correct command is upgrade indeed

**Comment by pagdot** [comment]
Ok, I'll open a PR to fix it :)
