### ISSUE TITLE
project  licence ??

### ISSUE THREAD

**Issue by elmissouri16** [PotatoProject/Leaflet#8]
Hey First thanks for sharing this project  I wanna use part of your code on my project I don't know much about how licensing work here on GitHub usually they're a tag on project indicate the license, so  can use or not and if yes what's I need to refer your code as open source and thank you again

**Comment by dvd-bnc** [comment]
You can use the code freely, the only thing you should do is credit me in some way (and maybe link to this repo) but that's it, for the rest you're free to do whatever you want

**Comment by elmissouri16** [comment]
ok thanks lot surely I will credit contributors of the project and link the repo

**Comment by IzzySoft** [comment]
@elmissouri16 that would mean something like [CC BY](https://opendefinition.org/licenses/cc-by/) then, right? E.g. [CC BY 4.0](https://opendefinition.org/licenses/cc-by/)? Mentioning that in the Readme would be great, so it's more easy to find :wink:
